"""Initial migration for Claims table

Revision ID: 001_initial_claims
Revises: 
Create Date: 2024-11-04 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '001_initial_claims'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claims',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('claim_number', sa.String(length=50), nullable=False),
    sa.Column('patient_name', sa.String(length=255), nullable=False),
    sa.Column('claim_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('RECEIVED', 'OCR_PROCESSING', 'PII_MASKED', 'DQ_VALIDATED', 'HUMAN_REVIEW', 'CONSENT_VERIFIED', 'CLAIM_VALIDATED', 'PAYER_SUBMITTED', 'SETTLED', 'REJECTED', name='claimstatus'), nullable=False),
    sa.Column('document_url', sa.Text(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('claim_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_number')
    )
    op.create_index('idx_claim_patient_status', 'claims', ['patient_name', 'status'], unique=False)
    op.create_index('idx_claim_status_created', 'claims', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_claims_claim_number'), 'claims', ['claim_number'], unique=False)
    op.create_index(op.f('ix_claims_id'), 'claims', ['id'], unique=False)
    op.create_index(op.f('ix_claims_status'), 'claims', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claims_status'), table_name='claims')
    op.drop_index(op.f('ix_claims_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_claim_number'), table_name='claims')
    op.drop_index('idx_claim_status_created', table_name='claims')
    op.drop_index('idx_claim_patient_status', table_name='claims')
    op.drop_table('claims')
    op.execute('DROP TYPE IF EXISTS claimstatus')
    # ### end Alembic commands ###