"""Add OCR fields to claims table

Revision ID: 002_ocr_fields
Revises: 001_initial_claims
Create Date: 2024-11-04 15:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '002_ocr_fields'
down_revision = '001_initial_claims'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claims', sa.Column('ocr_confidence_score', sa.Float(), nullable=True, comment='Overall confidence score from OCR processing (0.0-1.0)'))
    op.add_column('claims', sa.Column('ocr_processed_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when OCR processing completed'))
    op.add_column('claims', sa.Column('requires_human_review', sa.Boolean(), nullable=False, server_default='false', comment='Flag indicating if claim requires human review due to low confidence or errors'))
    op.create_index(op.f('ix_claims_requires_human_review'), 'claims', ['requires_human_review'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claims_requires_human_review'), table_name='claims')
    op.drop_column('claims', 'requires_human_review')
    op.drop_column('claims', 'ocr_processed_at')
    op.drop_column('claims', 'ocr_confidence_score')
    # ### end Alembic commands ###